MandelServer/Models/ErrorViewModel.cs
using System;

namespace MandelServer.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MandelServer/Controllers/FractalController.cs
using System.Diagnostics;
using MandelServer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DomainLogic;
using System.IO;
using System.Drawing.Imaging;
using Microsoft.Net.Http.Headers;
using MandelServer.Interfaces;

namespace MandelServer.Controllers
{
	public class FractalController : Controller
	{
		private readonly ILogger<FractalController> _logger;
		private readonly IMandelbrotGenerator _mandelbrotGenerator;

		public FractalController(ILogger<FractalController> logger, IMandelbrotGenerator mandelbrotGenerator)
		{
			_logger = logger;
			_mandelbrotGenerator = mandelbrotGenerator;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}


		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		[HttpGet]
		public async System.Threading.Tasks.Task<FileResult> MandelbrotAsync(double centerX, double centerY, double pixelToWorldScale, int numIterations)
		{
			var image = await _mandelbrotGenerator.GenerateAsync(centerX, centerY, pixelToWorldScale, numIterations);

			MemoryStream stream = new MemoryStream();
			image.Save(stream, ImageFormat.Gif);
			stream.Seek(0, SeekOrigin.Begin);
			return new FileStreamResult(stream, new MediaTypeHeaderValue("image/gif"))
			{
				FileDownloadName = "mandelbrot.gif"
			};
		}
	}
}

MandelServer/Views/Fractal/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<div class="text-center" id="imageContainer">

</div>

<div>
	Keys<br />
	Q - Zoom in<br />
	A - Zoom out<br />
	W - Increase max number of iterations<br />
	S - Decrease max number of iteration
</div>
<environment include="Development">
	<script src="~/js/mandelbrot.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
	<script src="~/js/mandelbrot.min.js" asp-append-version="true"></script>
</environment>

MandelServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MandelServer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Fractal" asp-action="Index">MandelServer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fractal" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MandelServer - <a asp-area="" asp-controller="Fractal" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>